### PR TITLE
fix finding instrument with serial number

### PR DESCRIPTION
**Pull request by ali65**

### CODE REVIEW

**Comment by alexforencich** [comment]
btag of zero is not allowed as per USBTMC spec.  I just pushed a fix for this yesterday.

**Comment by ali65** [comment]
Your yesterday's 'fix' was broken, it allowed the end up with 256 as btag.
Thanks for letting me know that zero is not allowed: I have check in the fix for that into my fork.

**Comment by alexforencich** [comment]
My 'fix' was borked because I only pushed it to my personal fork and I forgot to push it here.  

Anyway, what's the story with the serial number fix in your pull request?  It doesn't make sense according to the libusb code.  Are you using an old version of libusb?

**Comment by ali65** [comment]
Alex,
It appears that the latest version of pyusb,
http://sourceforge.net/p/pyusb/code/HEAD/tree/trunk/usb/util.py,
which I use, has the get_string defined as:
"def get_string(dev, length, index, langid = None)"

A line in your usbtmc.py was calling this function with only two arguments:
"s = usb.util.get_string(dev, dev.iSerialNumber)",
but 3 aguments are needed at least.

My solution,
"s = usb.util.get_string(dev, 256, dev.iSerialNumber)"
did make the it work.

Which version of pyusb are you using?

**Comment by alexforencich** [comment]
That repo has not been updated since 2011, it seems.  The page I am looking at is here: https://github.com/walac/pyusb/blob/master/usb/util.py#L244

**Comment by ali65** [comment]
Walac's code may be better, but for the uninformed users (like me), who install pyusb simply as "pip install pyusb" I guess the less pretty usb.util.get_string will be pulled (with the 'length' argument).

**Comment by alexforencich** [comment]
That's the official pyusb repo now.  The sourceforge one is deprecated.  I just downloaded the pyusb.tar.bz2 from https://pypi.python.org/pypi/pyusb and the definition there is

def get_string(dev, index, langid = None):

So it seems like you must be using a very old version of pyusb.

**Comment by ali65** [comment]
Thanks for investigating this. I confirm you are right.
I will try to find out how the outdated pyusb could get into that Linux system what I was using.  I don't have access to that system for a day (snow break), but I will update the story, if you care.

**Pull request closed without merging**
