### PR TITLE
Handful of minor fixes

### PR DESCRIPTION
**Pull request by SimplicityGuy**
* Minor refactoring of the kernel driver release
* Indentation issue for an if/else
* Bare minimal style changes (there are many more to do here to be pass pylint, pep8, flake8, etc, but this is a start)

### CODE REVIEW

**Comment by SimplicityGuy** [comment]
Any objections if I do a more extensive PEP8 cleanup?

**Comment by alexforencich** [comment]
Might as well.

**Comment by SimplicityGuy** [comment]
Ok, I'll get those done as a single PR. Additional features will be a separate PR.

**Comment by alexforencich** [comment]
What features are you thinking about adding?

**Comment by SimplicityGuy** [comment]
At the moment, none. As we get into using our instruments with `python-usbtmc` a bit more, we'll see. I have features in `python-ivi` to add more immediately (such as exposing a timeout property).

**Comment by alexforencich** [comment]
Gotcha.  I am going to go through all of the pull requests over the next couple of weeks and figure out what can be merged and what needs to be modified.  There was also one implementing Rigol quirks for usbtmc, I will have to see if I can get that one to apply.

**Pull request merged**
